export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_LIST_ADMIN_REQUEST = "ORDER_LIST_ADMIN_REQUEST";
export const ORDER_LIST_ADMIN_SUCCESS = "ORDER_LIST_ADMIN_SUCCESS";
export const ORDER_LIST_ADMIN_FAIL = "ORDER_LIST_ADMIN_FAIL";

export const ORDER_SERVED_REQUEST = "ORDER_SERVED_REQUEST";
export const ORDER_SERVED_SUCCESS = "ORDER_SERVED_SUCCESS";
export const ORDER_SERVED_FAIL = "ORDER_SERVED_FAIL";
export const ORDER_SERVED_RESET = "ORDER_SERVED_RESET";
